[custom]
; 使用你自己的 YAML 模板作为基础配置
clash_rule_base = https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/mysetting.yaml

; 允许节点自动注入到 proxy-groups
append_proxy = true
append_proxy_group = true

; 机场节点名称不过滤
exclude_remarks = 

; 允许所有节点进入 {{all}}
include_remarks = .*

; 自动测速节点进入 {{auto}}
enable_rule_generator = true
overwrite_original_rules = false

; 输出 Clash 格式
target = clash
