[custom]
clash_rule_base=https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/test.yaml
enable_rule_generator=true
overwrite_original_rules=true

########################################
# Rule Providers
########################################
rule-providers=Reject,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt,classical
rule-providers=YouTube,https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/rules/classical/YouTube.yaml,classical
rule-providers=Apple,https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/rules/classical/Apple.yaml,classical
rule-providers=Steam,https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/rules/classical/Steam.yaml,classical
rule-providers=OpenAI,https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/rules/classical/OpenAI.yaml,classical
rule-providers=OneDrive,https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/rules/classical/OneDrive.yaml,classical
rule-providers=Origin,https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/rules/classical/Origin.yaml,classical
rule-providers=Microsoft,https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/rules/classical/Microsoft.yaml,classical
rule-providers=EPIC,https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/rules/classical/EPIC.yaml,classical
rule-providers=Discord,https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/rules/classical/Discord.yaml,classical
rule-providers=Telegram,https://raw.githubusercontent.com/leeleok/openclash-ini/refs/heads/main/rules/classical/Telegram.yaml,classical

########################################
# Rules
########################################
ruleset=REJECT,RULE-SET,Reject
ruleset=REJECT,GEOSITE,CATEGORY-ADS-ALL

ruleset=DIRECT,DST-PORT,36540

ruleset=节点选择,DOMAIN-SUFFIX,vultr.com
ruleset=节点选择,DOMAIN-SUFFIX,nnr.moe

ruleset=DIRECT,DOMAIN-SUFFIX,istoreos.com
ruleset=DIRECT,DOMAIN-SUFFIX,wqyunpan.com
ruleset=DIRECT,DOMAIN-SUFFIX,leigod.com
ruleset=手动选择,DOMAIN-SUFFIX,maj-soul.com
ruleset=DIRECT,DOMAIN-SUFFIX,eeeknow.com
ruleset=DIRECT,DOMAIN-SUFFIX,zhongxinwanka.com
ruleset=DIRECT,DOMAIN-SUFFIX,bitwarden.com
ruleset=DIRECT,DOMAIN-SUFFIX,inzhi.online
ruleset=DIRECT,DOMAIN-SUFFIX,cftcredit.com
ruleset=DIRECT,DOMAIN-SUFFIX,lylend.com
ruleset=DIRECT,DOMAIN-SUFFIX,51credit.com
ruleset=DIRECT,DOMAIN-SUFFIX,yxmie.com
ruleset=DIRECT,DOMAIN-SUFFIX,benyingtc.com
ruleset=DIRECT,DOMAIN-SUFFIX,tjzimu.com
ruleset=DIRECT,DOMAIN-SUFFIX,fintopia.tech
ruleset=DIRECT,DOMAIN-SUFFIX,manmanbuy.com
ruleset=DIRECT,DOMAIN-SUFFIX,leelen.com
ruleset=PikPak,DOMAIN-SUFFIX,mypikpak.com

ruleset=DIRECT,PROCESS-NAME,aria2c
ruleset=DIRECT,PROCESS-NAME,qbittorrent-nox

ruleset=苹果服务,RULE-SET,Apple
ruleset=Steam,RULE-SET,Steam
ruleset=节点选择,RULE-SET,OpenAI
ruleset=微软云盘,RULE-SET,OneDrive
ruleset=微软服务,RULE-SET,Microsoft
ruleset=EPIC,RULE-SET,EPIC
ruleset=EA,RULE-SET,Origin
ruleset=节点选择,RULE-SET,Discord
ruleset=YouTube,RULE-SET,YouTube
ruleset=YouTube,RULE-SET,Telegram

ruleset=手动选择,GEOSITE,AMD
ruleset=手动选择,GEOSITE,TWITCH
ruleset=节点选择,GEOSITE,GOOGLE
ruleset=节点选择,GEOSITE,GOOGLE-CN

ruleset=节点选择,GEOIP,GOOGLE,no-resolve
ruleset=节点选择,GEOIP,GOOGLE-CN,no-resolve
ruleset=DIRECT,GEOIP,PRIVATE,no-resolve

ruleset=DIRECT,GEOSITE,PRIVATE
ruleset=手动选择,GEOSITE,GREATFIRE

ruleset=DIRECT,GEOIP,CN,no-resolve
ruleset=DIRECT,GEOSITE,CN

ruleset=手动选择,MATCH

########################################
# Proxy Groups
########################################
custom_proxy_group=量大专用`select`DIRECT
custom_proxy_group=日常选择`select`DIRECT
custom_proxy_group=自动切换`fallback`DIRECT`https://cp.cloudflare.com/generate_204`30
custom_proxy_group=节点选择`fallback`日常选择|自动切换|量大专用|DIRECT`https://cp.cloudflare.com/generate_204`30
custom_proxy_group=手动选择`select`日常选择|量大专用|自动切换|DIRECT

custom_proxy_group=YouTube`select`节点选择|DIRECT
custom_proxy_group=微软云盘`select`节点选择|DIRECT
custom_proxy_group=微软服务`select`节点选择|DIRECT
custom_proxy_group=苹果服务`select`节点选择|DIRECT
custom_proxy_group=EPIC`select`节点选择|DIRECT
custom_proxy_group=Steam`select`节点选择|DIRECT
custom_proxy_group=EA`select`节点选择|DIRECT
custom_proxy_group=PikPak`select`节点选择|DIRECT
